log.file.path: logs\cinemanote_app.log

server:
  port: 8080
  
jsondoc:
  version: 1.0
  basePath: http://localhost:${server.port}
  packages[0]: com.pikaso.home.cinemanote.view
  packages[1]: com.pikaso.home.cinemanote.service

spring:
  datasource:
    url: jdbc:h2:file:d:/temp/cinemanote/db/cinemanote.database;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa.hibernate:
    ddl-auto: none
    naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    use-new-id-generator-mappings: true
  h2.console.enabled: true

logging:
  file: ${log.file.path}
  level:
    com.pikaso.home.cinemanote: DEBUG
    org.springframework.web: INFO
    org.hibernate: WARN